### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#106]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12-215-g413023d (2016-10-29, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-215-g413023d (2016-10-29, branch "gaps-next") (pid 14392)
Loaded i3 config: /home/sans/.config/i3/config (Last modified: Sat Oct 15 21:00:54 2016, 1271158 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
i3 version 4.12-215-g413023d (2016-10-29, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```

i3 appears to be leaking memory in the latest version, as enabling logging through `i3-msg 'debuglog on; shmlog on; reload'` returns the following error:

```
[{"success":true},{"success":true},{"success":true}]

=================================================================
==12357==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f08170 in __interceptor_strdup /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_interceptors.cc:560
    #1 0x403722 in sstrdup ../../i3/libi3/safewrappers.c:45
    #2 0x402396 in main ../../i3/i3-msg/main.c:198
    #3 0x7f06801f3290 in __libc_start_main (/usr/lib/libc.so.6+0x20290)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f75210 in __interceptor_realloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:75
    #1 0x7f06808764e5 in yajl_alloc (/usr/lib/libyajl.so.2+0x14e5)
    #2 0x7f068087aa3f  (/usr/lib/libyajl.so.2+0x5a3f)

Indirect leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f74e60 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x7f068087646a in yajl_alloc (/usr/lib/libyajl.so.2+0x146a)
    #2 0x7f068087aa3f  (/usr/lib/libyajl.so.2+0x5a3f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f74e60 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x7f06808766de  (/usr/lib/libyajl.so.2+0x16de)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f74e60 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x7f068087892e  (/usr/lib/libyajl.so.2+0x392e)
    #2 0x7f068087aa3f  (/usr/lib/libyajl.so.2+0x5a3f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f0680f74e60 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x7f068087892e  (/usr/lib/libyajl.so.2+0x392e)

SUMMARY: AddressSanitizer: 407 byte(s) leaked in 6 allocation(s).
```

**Comment by Airblader** [comment]
Please report this upstream (github.com/i3/i3). Thanks.
